package clj.controller;

/**
 * This provide a interface for Controller to send Request to Model
 */
public interface ControllerModelInterface {
    /**
     * The function to receive the Request
     * @param request   The Request generated by the Controller
     * @return          The result generated by the Model
     */
    abstract int runRequest(Request request);
}
